import { Voiture } from "./voiture";

export const VOIYURES : Voiture[] =[
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 1,
        price:10009876543,
        carId: 1,
        name: "Audi A5 Sport back",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "assets/images/AudiA5Sportback.jpg",
        //carTypeId: number,
        type: "compacte"
        
    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 2,
        price:100,
        carId: 1,
        name: "BMW",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "assets/images/BMW.jpg",
        //carTypeId: number,
        type: "compacte"
    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 3,
        price:100,
        carId: 1,
        name: "BMW X5 xDrive 40 i1",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "assets/images/BMWX5xDrive40i1.jpg",
        //carTypeId: number,
        type: "compacte"

    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 4,
        price:100,
        carId: 1,
        name: "Fiat 500 c Abarth",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "assets/images/Fiat500cAbarth.jpg",
        //carTypeId: number,
        type: "compacte"

    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 5,
        price:100,
        carId: 1,
        name: "Ford Fiesta SE",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "assets/images/FordFiestaSE.jpg",
        //carTypeId: number,
        type: "compacte"

    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id:6,
        price:100,
        carId: 1,
        name: "Honda Fit EX",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "assets/images/HondaFitEX.jpg",
        //carTypeId: number,
        type: "compacte"

    },



    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 7,
        price:100,
        carId: 1,
        name: "Jeep Sahara",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "assets/images/JeepSahara.jpg",
        //carTypeId: number,
        type: "compacte"

    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 8,
        price:100,
        carId: 1,
        name: "Kia Forte",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "assets/images/KiaForte.jpg",
        //carTypeId: number,
        type: "compacte"
    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 9,
        price:100,
        carId: 1,
        name: "Kia Forte Ex",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "assets/images/KiaForteExRed.jpg",
        //carTypeId: number,
        type: "compacte"

    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 10,
        price:100,
        carId: 1,
        name: "Kia Forte LX",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "assets/images/KiaForteLX.jpg",
        //carTypeId: number,
        type: "compacte"
    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 11,
        price:100,
        carId: 1,
        name: "Kia Seltos",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "assets/images/KiaSeltos.jpg",
        //carTypeId: number,
        type: "compacte"
    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 12,
        price:100,
        carId: 1,
        name: "Mercedes-Benz",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "assets/images/Mercedes-Benz.jpg",
        //carTypeId: number,
        type: "compacte"

    },



    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 13,
        price:100,
        carId: 1,
        name: "peugeot",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"essence",
        hasAirConditioning: true,
        imageUrl: "https://thumbs.dreamstime.com/z/peugeot-blue-isolated-white-56027361.jpg",
        //carTypeId: number,
        type: "compacte"
    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 14,
        price:100,
        carId: 1,
        name: "",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"essence",
        hasAirConditioning: true,
        imageUrl: "https://thumbs.dreamstime.com/z/peugeot-blue-isolated-white-56027361.jpg",
        //carTypeId: number,
        type: "compacte"
    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 15,
        price:100,
        carId: 1,
        name: "",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"essence",
        hasAirConditioning: true,
        imageUrl: "https://thumbs.dreamstime.com/z/peugeot-blue-isolated-white-56027361.jpg",
        //carTypeId: number,
        type: "compacte"

    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 16,
        price:300,
        carId: 1,
        name: "ROYALTY-FREE STOCK PHOTO",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"essence",
        hasAirConditioning: true,
        imageUrl: "https://thumbs.dreamstime.com/b/red-car-3492923.jpg",
        //carTypeId: number,
        type: "compacte"

    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 17,
        price:1000,
        carId: 1,
        name: "Porche",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "https://thumbs.dreamstime.com/b/convertible-de-v%C3%A9hicule-de-bmw-335i-8477574.jpg",
        //carTypeId: number,
        type: "compacte"

    },
    {
        nom : "mehdi",
        createdAt: '30/08/1984 00:00',
        updatedAt: '30/08/1984 00:00',
        deletedAt: '30/08/1984 00:00',
        id: 18,
        price:1000,
        carId: 1,
        name: "Porche",
        //transmissionType: string,
        numberOfDoors: 4,
        numberOfBags: 3,
        numberOfSeats: 5,
        carburant:"diesel",
        hasAirConditioning: true,
        imageUrl: "https://thumbs.dreamstime.com/b/%C3%A9dition-jaune-de-tigre-de-bmw-m3-de-v%C3%A9hicule-16464749.jpg",
        //carTypeId: number,
        type: "compacte"

    }

];
